# Generated by Django 4.1.2 on 2022-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
