# Generated by Django 4.1.2 on 2022-11-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image2_article_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='section1',
        ),
        migrations.AddField(
            model_name='article',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
