# Generated by Django 4.1.2 on 2022-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_body_article_section1_article_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sectionLabel1',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
