# Generated by Django 4.1.2 on 2022-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_sectionlabel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sectionLabel2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='sectionLabel3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
